_____
**Write a program to create an array [10, 5, 7, 20, 15, -9, 33], print it, Find the maximum and minimum Value of the array**

In [ ]:
#Code here
import numpy as np

# Code here
arr = np.array([10, 5, 7, 20, 15, -9, 33])
print("Array:", arr)
print("Maximum value:", np.max(arr))
print("Minimum value:", np.min(arr))


Array: [10  5  7 20 15 -9 33]
Maximum value: 33
Minimum value: -9


______
**Write a program to accept an array of elements and find the maximum without using max function**

In [ ]:
#Code here
arr = list(map(int, input("Enter array elements separated by space: ").split()))
max_val = arr[0]

for num in arr[1:]:
    if num > max_val:
        max_val = num

print("Maximum value:", max_val)


Enter array elements separated by space: 1 4 5 7 8
Maximum value: 8


___
**Write a program to accept two matrices [[1,2],[3,4]],   [[2,4],[6,8]]and find the sum and subtraction of two matrices**

In [ ]:
#Code here
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 4], [6, 8]])

sum_matrix = A + B
sub_matrix = A - B

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Sum:\n", sum_matrix)
print("Subtraction:\n", sub_matrix)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[2 4]
 [6 8]]
Sum:
 [[ 3  6]
 [ 9 12]]
Subtraction:
 [[-1 -2]
 [-3 -4]]


___
**Write a program to generate a ranodom matrix of size 5 X 6. Add another row containing random elements to it. Find the sum of each row.**

In [2]:
#Code here
import numpy as np

matrix = np.random.randint(1, 100, (5, 6))
new_row = np.random.randint(1, 100, (1, 6))
updated_matrix = np.vstack([matrix, new_row])
row_sums = np.sum(updated_matrix, axis=1)

print("Matrix:\n", updated_matrix)
print("Row-wise sum:", row_sums)


Matrix:
 [[81 10 94 37 71 98]
 [16 64 69 16 78 89]
 [32 14 76  8 47  4]
 [88 30 33 85 40 26]
 [94 81 74  9 94 70]
 [38 72 25 43 91 78]]
Row-wise sum: [391 332 181 302 422 347]


___
**Write a program to generate a ranodm integer matrix of size 5 X 6. Add another column containing random integers to it. Compute the sine of each element and print it**

In [ ]:
#Code here
import numpy as np

matrix = np.random.randint(1, 100, (5, 6))
new_col = np.random.randint(1, 100, (5, 1))
updated_matrix = np.hstack([matrix, new_col])
sine_matrix = np.sin(np.radians(updated_matrix))

print("Updated Matrix:\n", updated_matrix)
print("Sine of each element:\n", sine_matrix)


Updated Matrix:
 [[10 96 87 89 92  1 37]
 [67 80  5 71 85 10 34]
 [51  4  9 33 57 54 14]
 [86 76 77  7 40  7 87]
 [74 26 44  1  6 11 52]]
Sine of each element:
 [[0.17364818 0.9945219  0.99862953 0.9998477  0.99939083 0.01745241
  0.60181502]
 [0.92050485 0.98480775 0.08715574 0.94551858 0.9961947  0.17364818
  0.5591929 ]
 [0.77714596 0.06975647 0.15643447 0.54463904 0.83867057 0.80901699
  0.2419219 ]
 [0.99756405 0.97029573 0.97437006 0.12186934 0.64278761 0.12186934
  0.99862953]
 [0.9612617  0.43837115 0.69465837 0.01745241 0.10452846 0.190809
  0.78801075]]


___
**Write a program to generate a ranodm matrix of size 5 X 6. Consider the 3rd and 4th row; and 2nd, 3rd and 4th column and print the resultant matrix using slicing**

In [ ]:
#Code here
import numpy as np
matrix = np.random.randint(1, 100, (5, 6))
sliced_matrix = matrix[2:4, 1:4]  # 3rd & 4th rows → index 2:4, 2nd–4th cols → 1:4

print("Original Matrix:\n", matrix)
print("Sliced Matrix (3rd-4th row, 2nd-4th col):\n", sliced_matrix)


Original Matrix:
 [[59 87 63 69 64 60]
 [49 84 52 64 15 23]
 [89  6 86 85  4 39]
 [21  8 99  4 88 41]
 [20 72 78  1 87 56]]
Sliced Matrix (3rd-4th row, 2nd-4th col):
 [[ 6 86 85]
 [ 8 99  4]]


### Great Job!